### PR TITLE
Update Russian translation.

### PR DESCRIPTION
**Pull request by vantu5z**

### CODE REVIEW

**Comment by jenslody** [comment]
Hi,
I just merged the (older) pull request #36, which also has changed ru.po .
Could you please check (and probably update) your pull-request, so I can do an automatically merge ?

Jens

**Comment by pinballwizard** [comment]
Hi,
Sorry, it's my fault. I did make two equal pull request.

**Comment by pinballwizard** [comment]
Hi, 
His translation have grammatical and semantical errors (about winds types and other). But i use his pull request for update mine. But don't merge this pull request over my.

**Comment by vantu5z** [comment]
Yes, pinballwizard translation is better. Think this pull request can be closed.

**Pull request closed without merging**
