### PR TITLE
More French fixes

### PR DESCRIPTION
**Pull request by DevDef**
- remove #,fuzzy tag on previous modifications (notably plural forms)
- nuke real fuzzy garbage
- uncapitalize day names
- typo: extention → extension
- other small fixes (units…)

### CODE REVIEW

**Comment by jenslody** [comment]
Merged into master.
Thank you for your contribution.

**Comment by jenslody** [comment]
I just reverted your changes from Dark Sky to darksky.net.
Dark Sky is the preferred naming according to their website.
And you can not just change the msgid in *.pot/*.po-files, you have to change the appropriate source file in this case also.

**Comment by jenslody** [comment]
Sorry I should not comment so late in the night.
I thought I switched from darksky.net to Dark Sky already, but something must have gon wrong there.
To much work the lastweeks.
Sorry.

**Comment by DevDef** [comment]
Perhaps a a non breaking space between Dark and Sky would have been better.
Please notice that each time you update the POT template file, every msgid strings modified are marked as “#,fuzzy” in all PO files. That means that they won’t be translated! So, they have to be updated too, at least to remove the fuzzy mark.
For example, you reverted my changes from darksky.net to Dark Sky, but the msgmerge after the xgettext has marked them as fuzzy and kinda broke them. :-/ This is fixed in my latest Git pull request. ;-)
Two little more things:
1. you changed some strings to add a space before some question or exclamation marks, as I did in my French string. You shouldn’t do this in English, this is a French typography rule (actually it is a thin [and so also non-breaking] space)
2. developer.geocode.farm is not a valid URL, it should be corrected (geocode.farm?)

**Pull request merged**
