### PR TITLE
add some japanese translations

### PR DESCRIPTION
**Pull request by WhiteCat6142**

### CODE REVIEW

**Comment by jenslody** [comment]
Thank you for your contribution.
One thing I want to ask before merging your pull-request:
can you please check the translations with the fuzzy-comment, at least one of your new translations has this.
String with the fuzzy-comment will not be used by the system, so if the translation is correct, please remove it (the fuzzy-comment) and update the pull-request.
If you think the fuzzy is correct, post it here and I will merge the pull-request as it is now.
Thank you.

Jens

**Comment by WhiteCat6142** [comment]
Thanks.
>...if the translation is correct, please remove it...
Ok,I try to understand them from when the strings is used.
And I am going to add more.
Because of them,it could be little longer to finish.

**Comment by WhiteCat6142** [comment]
done so well :D

**Comment by WhiteCat6142** [comment]
Oops,sorry.

**Pull request merged**
