### PR TITLE
Update Italian translation (100%)

### PR DESCRIPTION
**Pull request by Thema89**
Hi,

I've fixed some bad-translated entries and finished translating what was left undone.

### CODE REVIEW

**Comment by jenslody** [comment]
@Thema89:
Can you please overwork your translation (see @fitojb's comment) and remove the remaining "fuzzy"-comments (if the translation is correct).
Or confirm, that the translation with the fuzy-comments are correct and I do the changes.

**Comment by Thema89** [comment]
Sure, translation is correct but I totally forgot to remove that comment lines.
I'm going to push a clean version ASAP, including @fitojb's request for removing french spacing notation (it's not a _real_ error, but I can understand a good translation must be done in compliance with mainstream notation).

**Comment by Thema89** [comment]
@jenslody: now it's ready ;)

**Comment by jenslody** [comment]
Merged into master, thanks for your contribution in general and for updating the pull request.

**Pull request merged**
